### 


### Create Product

POST {{adminBase}}/products HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: multipart/form-data; boundary=createProducttBoundary

## productFields
# 1. prod name
--createProducttBoundary
Content-Disposition: form-data; name="productName"

testPro2
--createProducttBoundary
Content-Disposition: form-data; name="price"

200
--createProducttBoundary
Content-Disposition: form-data; name="discount"

20
--createProducttBoundary
Content-Disposition: form-data; name="subCategoryId"

sub3
--createProducttBoundary
Content-Disposition: form-data; name="image"; filename="testProd1.png"
Content-Type: image/png

< ~/Pictures/wallpapers/Night monochrome.jpg

# 2. The Data Parts
--createProducttBoundary
Content-Disposition: form-data; name="color"

red
--createProducttBoundary
Content-Disposition: form-data; name="size"

M
--createProducttBoundary
Content-Disposition: form-data; name="stock"

20
--createProducttBoundary--


# Content-Type: application/json
#
# {
#   "discount": 70,
#   "price": 2500,
#   "productName": "prod3",
#   "subCategoryId": "sub1"
# }


### Update Product

PATCH {{adminBase}}/products/7d1aa1b8-c8b9-4a9e-98a9-d643888e17a8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "publish": true
}


### Create Variant

POST {{adminBase}}/products/variants HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: multipart/form-data; boundary=createVariantBoundary

# 1. The File Part
--createVariantBoundary
Content-Disposition: form-data; name="image"; filename="testProd1Var5.png"
Content-Type: image/png

< ~/Pictures/wallpapers/clint-patterson-dYEuFB8KQJk-unsplash.jpg

# 2. The Data Parts
--createVariantBoundary
Content-Disposition: form-data; name="color"

yellow
--createVariantBoundary
Content-Disposition: form-data; name="price"

250
--createVariantBoundary
Content-Disposition: form-data; name="productId"

93a7d3ce-cc48-4a00-99a9-02dc7eff5f0d
--createVariantBoundary
Content-Disposition: form-data; name="size"

L
--createVariantBoundary
Content-Disposition: form-data; name="stock"

23
--createVariantBoundary--


### Update Variant

PATCH {{adminBase}}/products/variants/variant-002 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "stock": 4
}
