### 


### Find Products

GET {{base}}/products/prod-009 HTTP/1.1
Content-Type: application/json


### Find Products

GET {{base}}/products?cursor=prod-001&limit=2&subCategory=sub-men-tops HTTP/1.1
Content-Type: application/json


### Find Variants

GET {{base}}/products/variants HTTP/1.1
Content-Type: application/json


### Find Variants

GET {{base}}/products/getStockTotals/prod-001 HTTP/1.1
Content-Type: application/json
