### 

@base = http://localhost:8001/adminApi


### get orders

GET {{base}}/order-management?id=order_01 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}


### update order

PATCH {{base}}/order-management/order_01 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "status": "return_approved"
}


### finish refund

POST {{base}}/order-management/finishRefund/order_01 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}
