### 


### get orders

GET {{adminBase}}/order-management HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}


### update order

PATCH {{adminBase}}/order-management/bec3288d-3031-49ad-b795-c4a84cb2453a HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "status": "delivered"
}


### finish refund

POST {{adminBase}}/order-management/finishRefund/order_01 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{admin_token}}
