### 


### add item to cart

POST {{base}}/cart-management/addItem/variant-001 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{user_token}}


### Get Cart

GET {{base}}/cart-management HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{user_token}}


### Increase Quantity

PATCH {{base}}/cart-management/increaseQuantity/ce9c1db9-f481-4bd8-a2ef-1971b9547ce9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{user_token}}


### Decrease Quantity

PATCH {{base}}/cart-management/decreaseQuantity/ce9c1db9-f481-4bd8-a2ef-1971b9547ce9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{user_token}}


### Remove Item

DELETE {{base}}/cart-management/deleteItem/b4cfad7d-0de4-47fd-9234-cb0c93320e07 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{user_token}}


### claer cart

DELETE {{base}}/cart-management/clearCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{user_token}}
